version: 2

jobs:
  build:

    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r tests/requirements.txt
      - run:
          name: Run test
          command: |
            . ~/venv/bin/activate
            make test
