version: 2

jobs:
  build:

    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r tests/requirements.txt
      - run:
          name: Run test
          command: make test
